server:
  port: 8080

spring:
  application:
    name: sistema-saude
  data:
  kafka:
    bootstrap-server: localhost:9092
    producer:
      retries: 10
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializar: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false